[evm]

[evm.moonbase]
beneficiary = "0xf1fd5607b90f6c421db7313158baac170d4f053b"
block-confirmations = 0.0
chain-id = 1287.0
enabled = true
name = "moonbase"
private-key = "0xc086596a698603ae7428a61ced569cbc5fdc24ae91c341d692aad590febc4429"

[[evm.moonbase.contracts]]
address = "0x57f608d6561f0e354026f17f492c57311fd8080f"
contract = "VAnchor"

[evm.moonbase.contracts.events-watcher]
enabled = true
polling-interval = 1000.0
print-progress-interval = 7000.0

[[evm.moonbase.contracts.linked-anchors]]
address = "0x2552f59ff85602bff8043ca6ef94b1cbb14dc2c6"
chain-id = "80001"
type = "Evm"

[evm.moonbase.contracts.proposal-signing-backend]
node = "tangle"
type = "DKGNode"

[evm.moonbase.contracts.withdraw-config]
withdraw-fee-percentage = 0.0
withdraw-gaslimit = "0x5B8D80"

[[evm.moonbase.contracts]]
address = "0x12cec77a5ac7108ae453a7aeb6a31afc2b6f0bd8"
contract = "SignatureBridge"

[evm.moonbase.contracts.events-watcher]
enabled = true
polling-interval = 1000.0
print-progress-interval = 7000.0