[evm]

[evm.mumbai]
beneficiary = "0xf1fd5607b90f6c421db7313158baac170d4f053b"
block-confirmations = 0.0
chain-id = 80001.0
enabled = true
name = "mumbai"
private-key = "0xc086596a698603ae7428a61ced569cbc5fdc24ae91c341d692aad590febc4429"

[[evm.mumbai.contracts]]
address = "0x2552f59ff85602bff8043ca6ef94b1cbb14dc2c6"
contract = "VAnchor"

[evm.mumbai.contracts.events-watcher]
enabled = true
polling-interval = 1000.0
print-progress-interval = 7000.0

[[evm.mumbai.contracts.linked-anchors]]
address = "0x57f608d6561f0e354026f17f492c57311fd8080f"
chain-id = "1287"
type = "Evm"

[evm.mumbai.contracts.proposal-signing-backend]
node = "tangle"
type = "DKGNode"

[evm.mumbai.contracts.withdraw-config]
withdraw-fee-percentage = 0.0
withdraw-gaslimit = "0x5B8D80"

[[evm.mumbai.contracts]]
address = "0xca216c5dee21f69ff8ebaa32b26b0165bcd7d9c0"
contract = "SignatureBridge"

[evm.mumbai.contracts.events-watcher]
enabled = true
polling-interval = 1000.0
print-progress-interval = 7000.0