/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVAnchorVerifier816,
  IVAnchorVerifier816Interface,
} from "../IVAnchorVerifier816";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[29]",
        name: "input",
        type: "uint256[29]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "r",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVAnchorVerifier816__factory {
  static readonly abi = _abi;
  static createInterface(): IVAnchorVerifier816Interface {
    return new utils.Interface(_abi) as IVAnchorVerifier816Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVAnchorVerifier816 {
    return new Contract(address, _abi, signerOrProvider) as IVAnchorVerifier816;
  }
}
