/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IVerifier5, IVerifier5Interface } from "../IVerifier5";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[12]",
        name: "input",
        type: "uint256[12]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "r",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVerifier5__factory {
  static readonly abi = _abi;
  static createInterface(): IVerifier5Interface {
    return new utils.Interface(_abi) as IVerifier5Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVerifier5 {
    return new Contract(address, _abi, signerOrProvider) as IVerifier5;
  }
}
