[default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/',
    'src/=src/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config