name: Publish Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-docs:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    name: Publish Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies 
        run: |
          yarn install --production=false &&
          cd ./packages && yarn install
      - name: Generate docs
        run: |
          cd ./packages && npx typedoc --out docs index.ts 
  
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs 