name: Publish Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-docs:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    name: Publish Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies 
      - run: git submodule update --init --recursive
      - run: cd solidity-fixtures && dvc pull && cd ..
      - run: yarn install --production=false
      - run: yarn compile
      - run: yarn build:packages
      - run: cd ./packages/protocol-solidity && yarn install
      - name: Generate docs
        run: |
          cd ./packages/protocol-solidity && npx typedoc --out docs src/index.ts 
  
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./packages/protocol-solidity/docs