name: run-test-suite-2

on:
  push:
    branches: [ 'main' ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ '**' ]
    paths-ignore:
      - 'README.md'

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies 
        run: yarn install --production=false

      - name: clean
        run: yarn clean

      - name: Compile contracts
        run: lerna run compile --scope=@webb-tools/contracts
      - name: Compile identity contracts
        run: lerna run compile --scope @webb-tools/identity-anchor-contracts
      - name: Compile masp contracts
        run: lerna run compile --scope @webb-tools/masp-anchor-contracts

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
          
      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Populate fixtures
        run: yarn fetch:fixtures

      - name: Run test suite
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        run: yarn test
  
  # sets up build artifacts for other jobs to use
  identity-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies 
        run: yarn install --production=false

      - name: clean
        run: yarn clean

      - name: Compile contracts
        run: lerna run compile --scope=@webb-tools/contracts
      - name: Compile identity contracts
        run: lerna run compile --scope @webb-tools/identity-anchor-contracts
      - name: Compile masp contracts
        run: lerna run compile --scope @webb-tools/masp-anchor-contracts

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
          
      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Populate fixtures
        run: yarn fetch:fixtures

      - name: Run test suite
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        run: yarn test:identity

  # sets up build artifacts for other jobs to use
  masp-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies 
        run: yarn install --production=false

      - name: clean
        run: yarn clean

      - name: Compile contracts
        run: lerna run compile --scope=@webb-tools/contracts
      - name: Compile identity contracts
        run: lerna run compile --scope @webb-tools/identity-anchor-contracts
      - name: Compile masp contracts
        run: lerna run compile --scope @webb-tools/masp-anchor-contracts

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
          
      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Populate fixtures
        run: yarn fetch:fixtures

      - name: Run test suite
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        run: yarn test:masp
